### ISSUE TITLE
Millionaire:  German (Deutsch) language

### ISSUE THREAD

**Issue by KellerChr** [bdaloukas/moodle-mod_game#12]
Hello,

probably already known , there are at "millionaire" problems with the German language.

The 4 answer options are not A, B, C, D rather A, Ä, B, C.

I faced the problem a couple of days ago and found out, that the game.php file in the german language-pack a incorrect sorting of the german alphabet. 

The correct sorting of the german alphabet is: ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜß

That will fix the problem for the german language!

Kind regards,

Christopher

**Comment by bdaloukas** [comment]
Thank you for your message.
The last version fixes the problem.
Uses the string "'millionaire_lettersall'".
If the above string is "-" uses the string ""lettersall"
I send also to AMOS translation for the German language the translation of "'millionaire_lettersall' as "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

**Comment by KellerChr** [comment]
Hey,

thanks for your fast reply! 

Hm.. I think the decisive problem- is the wrong sort of alphabet in the language file.

If "'millionaire_lettersall'" is "-" then it uses the string "'lettersall'" (which has the wrong sorting of german alphabet). So even if the game.php in the DE language pack has the wrong sorting of the german alphabet, it will be display the wrong answer button.

whether there is a variable called lettersall or millionairs_lettersall

or am I thinking wrong? 

Kind regards,

Christopher

**Comment by bdaloukas** [comment]
The string "'lettersall'" is used also in Hangman so I created a new string named "millionaire_lettersall".
Please take a look at the last version of module Game and tell if it works ok.

**Comment by KellerChr** [comment]
Works great with the latest language-pack!

Kind regards,

Christopher

**Comment by KellerChr** [comment]
PS: The lettersall string (game.php in languagepack DE) is still sorted incorrectly. The german alphabet will spelled: ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜß

Kind regards :+1:

**Comment by bdaloukas** [comment]
I send "ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜß" to AMOS.
