### ISSUE TITLE
Design adjustments

### ISSUE THREAD

**Issue by KellerChr** [bdaloukas/moodle-mod_game#13]
Hey bdaloukas,

Just wanted to let you know that I'm doing some design adjustments at millionaire. 

Want to have these adjustments then? I have no experience with Github.

Kind regards,

Christopher

**Comment by KellerChr** [comment]
Will finish the design adjustments in a few days, how can i send you the touched file?

**Comment by bdaloukas** [comment]
When you finish you will tell me it and I will download the changed code.

**Comment by bdaloukas** [comment]
Do you finish the design adjustments? Do you attach also the changed file as a commend to this answer.
