### ISSUE TITLE
Error in SQL syntax during install

### ISSUE THREAD

**Issue by tpv-ebben** [bdaloukas/moodle-mod_game#17]
Error: Debug info: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows SMALLINT(3),
words SMALLINT(3),
wordsall BIGINT(10),
createscor' at line 4

[Gist with complete error](https://gist.github.com/tpv-ebben/b3b878719be70dc326c50fd662625035)

Moodle 3.3
MariaDB 10.2
mod_game commit 6ee163b, also same error with stable version

**Comment by bdaloukas** [comment]
Last beta version fixes the above problem.
Now the field is named "createdrows" instead "rows". "Rows" is a reserved word now in MariaDB.

**Comment by tpv-ebben** [comment]
there is another instance in snake_database, working on pull request

**Comment by bdaloukas** [comment]
I changed the table game_snakes_database also.
See the last stable release.

**Comment by tpv-ebben** [comment]
This is happening again with the latest version, 
`Debug info: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows SMALLINT(3) DEFAULT 0 AFTER id' at line 1
ALTER TABLE mdl_game_cross ADD rows SMALLINT(3) DEFAULT 0 AFTER id
Error code: ddlexecuteerror`
