### ISSUE TITLE
Icons in SVG and PNG

### ISSUE THREAD

**Issue by ralferlebach** [bdaloukas/moodle-mod_game#19]

**Comment by ralferlebach** [comment]
Sorry, the ticket accidentally went off before I had entered an description text which should read as follows:

Moodle supports sind 2.7 (I believe) SVG and PNG icons for activities. For this activity there are no such files in the /pix folder. Therefore I created an SVG mimicking the logo shown on moodle.org.

It would be great if those files could be enbundled in the next version of this great activity.

PS: github do not accept SVG files. Therfore I zipped it in order to be able to upload it.
[icon.zip](https://github.com/bdaloukas/moodle-mod_game/files/1155204/icon.zip)
![icon](https://user-images.githubusercontent.com/12737344/28308103-7ab1f610-6ba5-11e7-9c41-0eb04576f42a.png)

**Comment by bdaloukas** [comment]
Thank you. I enbundled them in the github version. It will be on the Moodle when I send the next version.
