### ISSUE TITLE
Book with question issue

### ISSUE THREAD

**Issue by pingtaoye** [bdaloukas/moodle-mod_game#23]
When clicking the "Associate question categories to chapter of book" in the Book with question in Moodle 3.5, it returns a blank page.

**Comment by DR-Bi** [comment]
Same. There doesn't appear to be a 'Turn editing on' button or menu option, either. 

And 'Book with Question' is a very important feature to replace the complicated 'Lesson' activity, so this unfortunately seems like another dead-end.

**Comment by bdaloukas** [comment]
I fixed some bugs in game "Book with questions" and works again. Thanks.
