### ISSUE TITLE
Make plugin GDPR compliant

### ISSUE THREAD

**Issue by ilyatregubov** [bdaloukas/moodle-mod_game#24]
Hello,

Since Moodle 3.5 all plugins should be GDPR compliant - they should notify if userdata is stored and provide a way to download/delete it. Is there a work going on for game plugin?

Thanks,
Ilya

**Comment by bdaloukas** [comment]
Is there any example of another plugin with is GDPR compliant or some documentation on Moodle?
I am making a new version and want to include this feature.

**Comment by ilyatregubov** [comment]
Hi,

So here is a documentation on privacy API in Moodle - https://docs.moodle.org/dev/Privacy_API

Here is an example of plugin where it has been implemented https://github.com/catalyst/moodle-tool_trigger/

Thanksm
Ilya

**Comment by bdaloukas** [comment]
Now Game module is GDPR compliant.
