### ISSUE TITLE
Typo in language string

### ISSUE THREAD

**Issue by temin** [bdaloukas/moodle-mod_game#32]
While translating Game plug-in I've noticed a typo in original string:
`$string[ 'cross_correct'] = 'corrert character';`

**Comment by markfromdel** [comment]
Checking lang/en/game.php, this appears to have been resolved.

> // File cross/crossdb_class.php.
> $string[ 'and'] = 'and';
> **$string[ 'cross_correct'] = 'correct character';**
> **$string[ 'cross_corrects'] = 'correct characters';**

This can be marked as closed if this meets the requirements of @temin .
