### ISSUE TITLE
Millionaire highlights incorrect response on wrong answer

### ISSUE THREAD

**Issue by markfromdel** [bdaloukas/moodle-mod_game#46]
Variable $stylequestionselected applies $color2 (defined as orange) and applies it to the selected button and answer on the page following an incorrect answer.

The button and answer combination that receives this orange color appears to be random, and most of the time is not applied to the answer selected by the user.

**Workaround**
I have found that a workaround is to change the variable $color2 to black.

**Work to do**
I haven't been able to trace in millionaire/play.php how the application of this orange color is done, and how it selects the answer based on the users response. Any help is appreciated. As I learn more about PHP, I will also try to contribute.

**Comment by bdaloukas** [comment]
Version 2021-12-23 fixes the problem. Please check it and close  it.
