### ISSUE TITLE
hiding game-type doesn´t work with Moodle 4.2 and pg

### ISSUE THREAD

**Issue by ksteitz** [bdaloukas/moodle-mod_game#54]
Today we updated our testing system from Moodle 4.1 to Moodle 4.2. Since then the config for hiding game-types doesn´t work anymore. Though types under /admin/settings.php?section=modsettinggame are set to hide (e.g. game | hidecross), they are shown in the activity chooser. The settings don´t matter, always most game-types are displyed in the chooser, except bookquiz and snakes. bookquiz and snakes are never shown in the chooser, even if the hidebookquiz and hidesnakes checkbox isn´t set. 

Moodle 4.2
PostgreSQL 13
PHP 8.0
mod_game: 2023-04-25 (2023042500)

general bug or just with our setting (using game already for many many years)? 
any ideas?

thanks!
Klaus

**Comment by AmelieSOUBRAT** [comment]
We have the same problem

**Comment by azrek** [comment]
That's because this line:

https://github.com/bdaloukas/moodle-mod_game/blob/MOODLE_20_STABLE/lib.php#L1233

Should be checking for:

`$name = 'hide'.$kind;`

not `$type`.

Thank you.

**Comment by t6nis** [comment]
add config too before..
$config = get_config('game');

$name = 'hide'.$kind;

**Comment by bdaloukas** [comment]
The problem is fixed.

**Comment by ksteitz** [comment]
Thanks a lot Vasilis!

cheers
Klaus
