### ISSUE TITLE
Crossword not working if you have two or more words in the same row/column

### ISSUE THREAD

**Issue by zmartinovic** [bdaloukas/moodle-mod_game#61]
There is a problem with referencing a question when you have tow or more words in the same row/column. In this case we get JS error and you can't enter an answer.
Problem is in how crossword references questions in legend and how it references it in JS code.
In legend if there is multiple words in the same row/column it will append letter to it (for example 8A, 8B, 8C...):
```
$this->mlegendh[$key.game_substr( $letters, $i, 1)] = $value[$i];
$this->mlegendv[$key.game_substr( $letters, $i, 1)] = $value[$i];
```
so it will create a DIV with that id:
```
<div id="a8A">
<div id="a8B">
```
but array passed to JS only refers to row/coll:
```
$swordx .= ",".($rec->mycol - 1);
$swordy .= ",".($rec->myrow - 1);
```
This is a problem because now you can't reference created DIV elements:
```
if( CurrentWord <= LastHorizontalWord) {
    id = 'a' + ( 1 + WordY[ CurrentWord]);
} else {
    id = 'd' + ( 1 + WordX[ CurrentWord]);
}
document.getElementById("wordclue").innerHTML = document.getElementById( id).innerHTML;
```
var id will only have value "a8" but there is DIV element with this id.
![sc1](https://github.com/bdaloukas/moodle-mod_game/assets/8968916/8bfa9f18-bdaf-4011-840b-d0e152071aa5)
![sc2](https://github.com/bdaloukas/moodle-mod_game/assets/8968916/5fba7c7e-5399-4c47-8237-445222853519)
![sc3](https://github.com/bdaloukas/moodle-mod_game/assets/8968916/90a6bc83-8d84-4aaf-a09e-6f7e451f138f)

**Comment by bdaloukas** [comment]
Version 2023111400 fixes the above problem.
