### ISSUE TITLE
Error: Wrong questions are shown in Moodle 4.0+ for quizzes

### ISSUE THREAD

**Issue by AraPraxis** [bdaloukas/moodle-mod_game#64]
I noticed that in the 04.00+ version of the plugin, a specfic select is used to get all question_references on a quiz_slot
![image](https://github.com/bdaloukas/moodle-mod_game/assets/89771146/09907f44-cd39-4c0d-8ecc-a8b1526997f0)

This has given an error when the quiz_slot id and question_reference id is not the same, wrong questions are shown on the correct chosen quiz.

I've looked at Moodle's ERD and it looks like the correct SQL should be:
"qs.quizid='$game->quizid' AND qs.id=qr.itemid ";

https://www.examulator.com/er/4.2/tables/quiz_slots.html
https://www.examulator.com/er/4.2/tables/question_references.html

**Comment by bdaloukas** [comment]
Thank you. I accept your proposal in version 20231102
