### ISSUE TITLE
Prevent Style Override of Crossword

### ISSUE THREAD

**Issue by AndreScherl** [bdaloukas/moodle-mod_game#8]
The Crossword stylings in cross/play.php line 146 to 260 need a container, e.g. #region-main to prevent the style overrides of h1, h2, etc.

For example: `h1 {}` becomes `#region-main h1 {}`
You should change this for all custom game stylings.

I checked it in our custom theme and the clean theme as well.

Thanks and best regards
Andre

**Comment by bdaloukas** [comment]
I made the change you proposed. Please, take a look on it.

**Comment by AndreScherl** [comment]
I did not test the code but I think you did. Your changes are looking good.
Thanks!
